### ISSUE TITLE
JSON rather than XML ;-)

### ISSUE THREAD

**Issue by rufuspollock** [CircuitData/CircuitData-Language#2]
JSON is much "nicer" than XML: lighter-weight, easier to read. And it is a better fit for a web-oriented world -- natively parseable in the browser.

**Comment by alydersen** [comment]
The reason why I started this as XML was that I wanted it to be possible to integrate into the [IPC 2581](http://www.ipc2581.com/) format/standard. The original idea of this was to have this whole effort as part of 2581 and possible to transmit as a fabrication data "partial".

I was actually thinking to create an "OpenTradeXML" that would contain all the logistical information as owner and created date, etc. But maybe we could use frictionless data for that? And add this data as a source? Most of the time, this xml would be sent together with other data, such as the cad-files, and they could all be referenced as sources.

Since we haven't used any parameters in the XML, we could allow the use of both XML and JSON I guess.

**Comment by alydersen** [comment]
I've changed this so that it can be used for both XML and JSON. Also, most of the generic/non-pcb stuff is separated into a different project: https://github.com/elmatica/Open-Trade-Transfer-Package

Will create more examples later on.

**Comment by rufuspollock** [comment]
Great!
